export type Role = 'admin' | 'rider' | 'driver';
export type RideStatus = 'REQUESTED' | 'MATCHING' | 'DRIVER_ASSIGNED' | 'DRIVER_ARRIVING' | 'DRIVER_WAITING' | 'TRIP_STARTED' | 'TRIP_COMPLETED' | 'PAYMENT_PENDING' | 'COMPLETED' | 'CANCELLED';
export type VehicleType = 'Standard' | 'Premium' | 'XL';
export interface User { id: string; name: string; phone: string; email?: string; role: Role; status: 'Active' | 'Suspended'; }
export interface Driver { id: string; userId: string; name: string; licenseNumber: string; onboardingStatus: 'Pending' | 'Approved' | 'Rejected'; availabilityStatus: 'Offline' | 'Available' | 'OnTrip'; rating: number; vehicle?: { type: VehicleType; make: string; model: string; registrationNumber: string; }; }
export interface Ride { id: string; riderId: string; riderName: string; driverId?: string; driverName?: string; status: RideStatus; vehicleType: VehicleType; pickup: string; destination: string; estimatedFare: number; currency: string; requestedAtUtc: string; }
export interface Payment { id: string; rideId: string; amount: number; currency: string; method: 'Cash' | 'Online'; status: 'Pending' | 'Processing' | 'Succeeded' | 'Failed' | 'Refunded'; createdAtUtc: string; }
export interface Estimate { baseFare: number; distanceFare: number; durationFare: number; bookingFee: number; taxes: number; discount: number; total: number; }
export interface Dashboard { activeRides: number; activeDrivers: number; completedRides: number; revenue: number; assignmentRate: number; paymentSuccessRate: number; }

const API_URL = (import.meta.env.VITE_API_URL as string | undefined)?.replace(/\/$/, '') ?? '';
const USE_MOCKS = import.meta.env.VITE_USE_MOCKS !== 'false';
const now = () => new Date().toISOString();
const currentUser: User = { id: 'user-rider-1', name: 'Alex Morgan', phone: '+1 555 0101', email: 'alex@example.com', role: 'rider', status: 'Active' };
const mockUsers: User[] = [currentUser, { id: 'user-driver-1', name: 'Jordan Lee', phone: '+1 555 0102', role: 'driver', status: 'Active' }, { id: 'user-admin-1', name: 'Operations Admin', phone: '+1 555 0103', role: 'admin', status: 'Active' }];
const mockDrivers: Driver[] = [{ id: 'driver-1', userId: 'user-driver-1', name: 'Jordan Lee', licenseNumber: 'DL-482901', onboardingStatus: 'Approved', availabilityStatus: 'Available', rating: 4.9, vehicle: { type: 'Standard', make: 'Toyota', model: 'Camry', registrationNumber: 'RIDE-101' } }, { id: 'driver-2', userId: 'user-driver-2', name: 'Sam Rivera', licenseNumber: 'DL-198220', onboardingStatus: 'Pending', availabilityStatus: 'Offline', rating: 4.7 }];
let mockRides: Ride[] = [{ id: 'ride-1001', riderId: currentUser.id, riderName: currentUser.name, driverId: 'driver-1', driverName: 'Jordan Lee', status: 'TRIP_STARTED', vehicleType: 'Standard', pickup: '221B Baker Street', destination: 'Heathrow Airport', estimatedFare: 32.5, currency: 'USD', requestedAtUtc: now() }, { id: 'ride-1000', riderId: 'user-22', riderName: 'Taylor Smith', status: 'COMPLETED', vehicleType: 'Premium', pickup: 'Downtown', destination: 'North Station', estimatedFare: 26.2, currency: 'USD', requestedAtUtc: now() }];
const mockPayments: Payment[] = [{ id: 'pay-1', rideId: 'ride-1000', amount: 26.2, currency: 'USD', method: 'Online', status: 'Succeeded', createdAtUtc: now() }];
async function request<T>(path: string, init?: RequestInit): Promise<T> { if (USE_MOCKS || !API_URL) return mockRequest<T>(path, init); const response = await fetch(`${API_URL}${path}`, { ...init, headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${localStorage.getItem('accessToken') ?? ''}`, ...(init?.headers ?? {}) } }); if (!response.ok) { const error = await response.json().catch(() => ({})); throw new Error(error.message ?? `Request failed (${response.status})`); } return response.status === 204 ? (undefined as T) : response.json(); }
async function mockRequest<T>(path: string, init?: RequestInit): Promise<T> { await new Promise(resolve => setTimeout(resolve, 180)); if (path === '/api/v1/admin/riders') return mockUsers.filter(x => x.role === 'rider') as T; if (path === '/api/v1/admin/drivers') return mockDrivers as T; if (path === '/api/v1/admin/rides') return mockRides as T; if (path === '/api/v1/admin/payments') return mockPayments as T; if (path.startsWith('/api/v1/rides/history')) return mockRides.filter(x => x.riderId === currentUser.id) as T; if (path.startsWith('/api/v1/drivers/') && path.endsWith('/rides/active')) return mockRides.filter(x => x.driverId === 'driver-1' && !['COMPLETED', 'CANCELLED'].includes(x.status)) as T; if (path.startsWith('/api/v1/drivers/') && path.endsWith('/earnings')) return 1284.5 as T; if (path === '/api/v1/rides/estimate') return { baseFare: 3, distanceFare: 14.4, durationFare: 4.5, bookingFee: 1, taxes: 1.15, discount: 0, total: 24.05 } as T; if (path === '/api/v1/rides' && init?.method === 'POST') { const body = JSON.parse(String(init.body)); const ride: Ride = { id: `ride-${Date.now()}`, riderId: currentUser.id, riderName: currentUser.name, status: 'MATCHING', vehicleType: body.vehicleType, pickup: body.pickupAddress, destination: body.destinationAddress, estimatedFare: 24.05, currency: 'USD', requestedAtUtc: now() }; mockRides = [ride, ...mockRides]; return ride as T; } if (path === '/api/v1/auth/register') { const body = JSON.parse(String(init?.body)); return { userId: crypto.randomUUID(), accessToken: 'mock-access', refreshToken: 'mock-refresh', role: body.role } as T; } if (path === '/api/v1/auth/login') return { userId: currentUser.id, accessToken: 'mock-access', refreshToken: 'mock-refresh', role: currentUser.role } as T; return {} as T; }
export const api = { register: (payload: { phoneNumber: string; email?: string; firstName: string; lastName?: string; password: string; role: Role }) => request<{ userId: string; accessToken: string; refreshToken: string; role: Role }>('/api/v1/auth/register', { method: 'POST', body: JSON.stringify(payload) }), login: (phone: string, password: string) => request<{ userId: string; accessToken: string; refreshToken: string; role: Role }>('/api/v1/auth/login', { method: 'POST', body: JSON.stringify({ phoneNumber: phone, password }) }), riders: () => request<User[]>('/api/v1/admin/riders'), drivers: () => request<Driver[]>('/api/v1/admin/drivers'), rides: () => request<Ride[]>('/api/v1/admin/rides'), payments: () => request<Payment[]>('/api/v1/admin/payments'), history: (userId: string) => request<Ride[]>(`/api/v1/rides/history?userId=${encodeURIComponent(userId)}`), activeRide: (userId: string) => request<Ride | null>(`/api/v1/rides/active?userId=${encodeURIComponent(userId)}`), driverActiveRides: (driverId: string) => request<Ride[]>(`/api/v1/drivers/${driverId}/rides/active`), earnings: (driverId: string) => request<number>(`/api/v1/drivers/${driverId}/earnings`), estimate: (payload: unknown) => request<Estimate>('/api/v1/rides/estimate', { method: 'POST', body: JSON.stringify(payload) }), createRide: (payload: unknown) => request<Ride>('/api/v1/rides', { method: 'POST', body: JSON.stringify(payload) }), updateAvailability: (driverId: string, status: string) => request<Driver>(`/api/v1/drivers/${driverId}/availability`, { method: 'PUT', body: JSON.stringify({ status }) }), transition: (rideId: string, action: string, userId: string) => request<Ride>(`/api/v1/rides/${rideId}/${action}`, { method: 'POST', body: JSON.stringify({ userId }) }), pay: (rideId: string, method: string) => request<Payment>(`/api/v1/rides/${rideId}/payment`, { method: 'POST', body: JSON.stringify({ method }) }), rate: (rideId: string, userId: string, score: number, comment: string) => request(`/api/v1/rides/${rideId}/rating`, { method: 'POST', body: JSON.stringify({ userId, score, comment }) }) };
export function getMockDashboard(data: { rides: Ride[]; drivers: Driver[]; payments: Payment[] }): Dashboard { const completed = data.rides.filter(x => x.status === 'COMPLETED').length; return { activeRides: data.rides.filter(x => !['COMPLETED', 'CANCELLED'].includes(x.status)).length, activeDrivers: data.drivers.filter(x => x.availabilityStatus === 'Available').length, completedRides: completed, revenue: data.payments.filter(x => x.status === 'Succeeded').reduce((s, x) => s + x.amount, 0), assignmentRate: data.rides.length ? Math.round(data.rides.filter(x => x.driverId).length / data.rides.length * 100) : 0, paymentSuccessRate: data.payments.length ? Math.round(data.payments.filter(x => x.status === 'Succeeded').length / data.payments.length * 100) : 0 }; }
