using RideHailing.Domain;

namespace RideHailing.Application;

public sealed class RideWorkflowService(ApplicationStore store, FareCalculator calculator, IPaymentProvider paymentProvider)
{
    public Ride Create(Guid riderId, CreateRideInput input, CancellationToken ct) { if (!store.Users.ContainsKey(riderId)) throw new DomainException("RIDER_NOT_FOUND", "Rider was not found."); var ride = new Ride(riderId, input.VehicleType, input.Pickup, input.PickupAddress, input.Destination, input.DestinationAddress); var km = Distance(ride.Pickup, ride.Destination); ride.SetEstimate((int)(km * 1000), (int)(km * 120), calculator.Calculate(input.Pricing, (decimal)km, (decimal)(km * 2), input.Discount).Total); ride.TransitionTo(RideStatus.Matching); store.Rides[ride.Id] = ride; return ride; }
    public Ride? Get(Guid id) => store.Rides.GetValueOrDefault(id);
    public Ride Cancel(Guid id, Guid actor, string reason) { var ride = Require(id); if (ride.RiderId != actor && ride.DriverId != actor) throw new DomainException("FORBIDDEN", "The user does not belong to this ride."); ride.TransitionTo(RideStatus.Cancelled, actor, reason); return ride; }
    public Ride Advance(Guid id, Guid driverId, RideStatus next) { var ride = Require(id); if (ride.DriverId != driverId) throw new DomainException("FORBIDDEN", "Driver is not assigned to this ride."); ride.TransitionTo(next, driverId); if (next == RideStatus.TripCompleted) { ride.SetFinalFare(ride.EstimatedFare ?? 0); ride.TransitionTo(RideStatus.PaymentPending); } return ride; }
    public RideOffer Offer(Guid rideId, Guid driverId, TimeSpan duration) { var ride = Require(rideId); if (ride.Status != RideStatus.Matching) throw new DomainException("RIDE_NOT_MATCHING", "Ride is not available for matching."); var driver = store.Drivers.GetValueOrDefault(driverId) ?? throw new DomainException("DRIVER_NOT_FOUND", "Driver was not found."); if (driver.AvailabilityStatus != DriverAvailabilityStatus.Available || !store.Vehicles.Values.Any(v => v.DriverId == driverId && v.VehicleType == ride.VehicleType && v.Status == VehicleStatus.Active)) throw new DomainException("DRIVER_NOT_ELIGIBLE", "Driver is not eligible for this ride."); var offer = new RideOffer(rideId, driverId, DateTime.UtcNow.Add(duration)); store.Offers[OfferKey(rideId, driverId)] = offer; return offer; }
    public Ride Accept(Guid rideId, Guid driverId) { var key = OfferKey(rideId, driverId); if (!store.Offers.TryGetValue(key, out var offer) || offer.IsExpired) throw new DomainException("RIDE_OFFER_EXPIRED", "Ride offer is expired or missing."); var ride = Require(rideId); lock (ride) { if (!ride.TryAssign(driverId)) throw new DomainException("RIDE_ALREADY_ASSIGNED", "Ride has already been assigned."); store.Offers.TryRemove(key, out _); return ride; } }
    public Ride Reject(Guid rideId, Guid driverId) { store.Offers.TryRemove(OfferKey(rideId, driverId), out _); return Require(rideId); }
    public Payment Pay(Guid rideId, PaymentMethod method) { var ride = Require(rideId); if (ride.Status != RideStatus.PaymentPending) throw new DomainException("PAYMENT_NOT_DUE", "Payment is not due for this ride."); var payment = new Payment(rideId, method, ride.FinalFare ?? ride.EstimatedFare ?? 0, ride.Currency); store.Payments[payment.Id] = payment; if (method == PaymentMethod.Cash) { payment.Mark(PaymentStatus.Succeeded); ride.TransitionTo(RideStatus.Completed); } else { var result = paymentProvider.CreatePaymentAsync(new(rideId, payment.Amount, payment.Currency, $"payment:{rideId}:final"), CancellationToken.None).GetAwaiter().GetResult(); payment.Mark(result.Status, result.ProviderReference); if (result.Status == PaymentStatus.Succeeded) ride.TransitionTo(RideStatus.Completed); } return payment; }
    public Rating Rate(Guid rideId, Guid rater, byte score, string? comment) { var ride = Require(rideId); if (ride.Status != RideStatus.Completed || ride.DriverId is null) throw new DomainException("RIDE_NOT_COMPLETED", "Only completed rides can be rated."); if (store.Ratings.Values.Any(x => x.RideId == rideId && x.RaterUserId == rater)) throw new DomainException("RATING_EXISTS", "A rating has already been submitted."); var rating = new Rating(rideId, rater, ride.DriverId.Value, score, comment); store.Ratings[rating.Id] = rating; return rating; }
    public void UpdateLocation(Guid driverId, Guid rideId, GeoPoint position, double accuracy, double? heading, double? speed) { var ride = Require(rideId); if (ride.DriverId != driverId || !position.IsValid) throw new DomainException("INVALID_LOCATION", "Location is invalid or driver is not assigned."); store.Locations[driverId] = new(driverId, position, accuracy, heading, speed, DateTime.UtcNow); }
    private Ride Require(Guid id) => store.Rides.GetValueOrDefault(id) ?? throw new DomainException("RIDE_NOT_FOUND", "Ride was not found.");
    private static string OfferKey(Guid ride, Guid driver) => $"{ride}:{driver}";
    private static double Distance(GeoPoint a, GeoPoint b) => Math.Sqrt(Math.Pow((b.Latitude - a.Latitude) * 111, 2) + Math.Pow((b.Longitude - a.Longitude) * 111, 2));
}
