<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RideHailing.Application\RideHailing.Application.csproj" />
    <ProjectReference Include="..\RideHailing.Infrastructure\RideHailing.Infrastructure.csproj" />
    <ProjectReference Include="..\RideHailing.Contracts\RideHailing.Contracts.csproj" />
    <ProjectReference Include="..\RideHailing.Domain\RideHailing.Domain.csproj" />
  </ItemGroup>

</Project>
